eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
    fetchRegistry: true

#ribbon:
#  eureka:
#    enabled: false
#
service-consumer:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8081

#zuul:
#  prefix: /proxy
#  routes:
#    service-consumer: /service-consumer/**
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "info,health,refresh"
#
#ribbon:
#  eureka:
#    enabled: true
#
#info:
#  app:
#    name: ${spring.application.name}
#  company:
#    name: www.etoak.com